---
name: Params-Smart
version: 0.08
author:
  - 'Robert Rothenberg <rrwo at cpan.org>'
abstract: use both positional and named arguments in a subroutine
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Regexp::Common: 1.8
  perl: 5.6.0
build_requires:
  Test::More: 0
recommends:
  Pod::Readme: 0.02
provides:
  Params::Smart:
    file: lib/Params/Smart.pm
    version: 0.08
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
